### ISSUE TITLE
Todo for first release

### ISSUE THREAD

**Issue by LinguList** [digling/character-formation-paper#1]
- [ ] complete code
- [x] make a test with sinopy as single dependency 
- [x] add pandoc as requirement for conversion to pdf
- [x] fill in the readme
- [ ] submit all data
- [ ] first release (with code then shared)
- [ ] statement how to quote the package
